name: Sync Forked Repository

on:
  schedule:
    - cron: '0 0 */6 * *' # 每天UTC 00:00执行
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Sync with upstream
      run: |
        git remote add upstream https://github.com/PublicAffairs/openai-gemini.git  # 替换为原始仓库的 URL
        git fetch upstream
        git checkout main  # 替换为你的主分支
        git merge --allow-unrelated-histories -X theirs --no-edit upstream/main  # 强制使用原始仓库的更改
        git push origin ${{ github.head_ref }} --force # 强制推送到当前分支

      env:
        PAT: ${{ secrets.PAT }}
